language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
before_script:
  - export PYTHONPATH=`pwd`
# command to run tests
script: nosetests --with-coverage tests/ --cover-package=bucketlist
after_success:
  - coveralls