language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
# command to run tests
script: "nosetests --with-coverage --cover-package=bucketlist"
after_success:
  - coveralls